### ISSUE TITLE
[Question] book depository API

### ISSUE THREAD

**Issue by asyba** [sp1thas/book-depository-dataset#14]
Hi
From where I can get the _authenticationKey_ and _clientId_ to use the BD API? also do you know endpoints that can return stock availability? 

Thanks

**Comment by sp1thas** [comment]
Hey @asyba , I'm not aware of the book depository API at all. This project uses web scraping techniques to acquire the data. Regardings your second question, you can take a look on [RapidAPI](https://rapidapi.com/category/Finance)

**Comment by asyba** [comment]
> Hey @asyba , I'm not aware of the book depository API at all. This project uses web scraping techniques to acquire the data. Regardings your second question, you can take a look on [RapidAPI](https://rapidapi.com/category/Finance)

but did you scrap bookdepository.com and found those api urls, querys, clientId data, etc?
I tried RapidAPI but there is nothing about bookdepository

**Comment by sp1thas** [comment]
> but did you scrap bookdepository.com and found those api urls, querys, clientId data, etc?

I use a [list of category urls](https://github.com/sp1thas/book-depository-dataset/blob/master/bdepo/spiders/bdepobooks.py#L21) (generated by hand) as a scrapping start point. Every other url is auto-discovered during the crawling process. No queries, no client-related data.

> I tried RapidAPI but there is nothing about bookdepository

My bad, I thought you are looking for stock market data. I think that book depository doesn't provide any kind of information about the stock availability. From my POV, this is the only assumption you can make: Any listed book is in stock.
